version: '3.8'

services:
  client:
    build: 
      context: .
      dockerfile: ./src/client/Dockerfile
    container_name: client_frontend
    ports:
      - 8000:8000
    volumes:
      - ./src/client:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
  api:
    build: 
      context: .
      dockerfile: ./src/server/Dockerfile
    container_name: api_backend
    ports:
      - 5000:5000
    volumes:
      - ./src/server:/app
      - ./app/node_modules
    stdin_open: true
    tty: true