version: '3.8'

services:
  api:
    build: ./server
    container_name: api_backend
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  client:
    build: 
      context: .
      dockerfile: client/Dockerfile
    container_name: client_frontend
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true