version: '3.8'



services:
  api:
    build: 
      context: .
      dockerfile: server/Dockerfile
      args:
        - SERVER_PORT=$SERVER_PORT
    container_name: api_backend
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
  client:
    build: 
      context: .
      dockerfile: client/Dockerfile
      args:
        - ${CLIENT_PORT}=${CLIENT_PORT}
    container_name: client_frontend
    env_file:
      - .env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./:/app
    stdin_open: true
    tty: true