version: '3.8'

services:
  api:
    build: ./server
    container_name: api_backend
    ports:
      - '5000:5000'
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
  client:
    build: 
      context: .
      dockerfile: client/Dockerfile
    container_name: client_frontend
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    stdin_open: true
    tty: true