version: '3.8'



services:
  api:
    build: 
      context: server
      dockerfile: Dockerfile
      args:
        - SERVER_PORT=$SERVER_PORT
    container_name: api_backend
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/app/server
      - /app/server/node_modules/
    stdin_open: true
    tty: true
  client:
    build: 
      context: client
      dockerfile: Dockerfile
      args:
        - ${CLIENT_PORT}=${CLIENT_PORT}
    container_name: client_frontend
    env_file:
      - .env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client:/app/client
      - /app/client/node_modules/

    stdin_open: true
    tty: true
